// client-vue/src/features/passwordInput/PasswordInput.vue
<script>
export default {
    name: 'password-input',
    props: {
        modelValue: [String]
    },
    data() {
        return {
            isActive: false,
            isError: false,
            isVisible: false
        }
    },
    methods: {
        updateInput(event) {
            this.$emit('update:modelValue', event.target.value)
        },
        onFocusHandler() {
            this.isActive = true
            this.isError = false
        },
        onBlurHandler() {
            if(!this.modelValue) {
                this.isError = true
                this.isActive = false
            }
        },
        togleVisible() {
            this.isVisible = !this.isVisible
        }
    }
}
</script>


<template>
    <div class="passwordInputContainer" :class="{ error: isError}">
        <input
            :type="isVisible ? 'text' : 'password'"
            :value="modelValue" 
            @input="updateInput"
            @focus="onFocusHandler" 
            @blur="onBlurHandler"
        >
        <img 
            @click="this.togleVisible"
            src="../../shared/img/eye.svg" 
            alt="visible" 
            class="togleVisible"
        >
        <span class="placeholder" :class="{ active: isActive}">
            Password
        </span>
        <span v-if="this.isError" class="errorMessage">
            Field is required!
        </span>
    </div>
</template>


<style scoped>
.passwordInputContainer {
    position: relative;
    width: 100%;
    height: 64px;
    border-radius: 4px;
}
.passwordInputContainer > input {
    width: 100%;
    height: 100%;
    position: absolute;
    z-index: 100;
    padding: 16px 16px 0 16px;
    outline: none;
    border-radius: 4px;
    border: 1px solid rgba(242, 242, 242, 1);
    background: transparent;
}
.passwordInputContainer > input::-ms-reveal {
    display: none;
}

.passwordInputContainer > img {
    width: 16px;
    height: 16px;
    position: absolute;
    z-index: 100;
    right: 16px;
    bottom: 24px;
    cursor: pointer;
}
.placeholder {
    position: absolute;
    left: 16px;
    top: 24px;
    z-index: 10;
    color: rgba(128, 128, 128, 1);
    transition: all ease 0.1s;
}
.active {
    position: absolute;
    font-size: 12px;
    line-height: 14.4px;
    top: 16px;
    left: 16px;
    color: rgba(128, 128, 128, 1);
    transition: all ease 0.1s;
}
.error {
    border: 1px solid #DC0B35;
}
.errorMessage {
    position: absolute;
    display: block;
    bottom: 0;
    left: 16px;
    color: #DC0B35;
    font-size: 10px;
}
</style>

// client/src/features/PasswordInput/PasswordInput.tsx
import { FC, useState } from 'react'
import eye from '../../shared/images/eye.svg'
import styles from './PasswordInput.module.scss'


type Props = {
    password: string,
    setPassword: (password: string) => void
}


const PasswordInput: FC<Props> = ({
    password,
    setPassword
}) => {

    const [isVisible, setIsVisible] = useState<boolean>(false)
    const [isFocused, setIsFocused] = useState<boolean>(false)
    const [isError, setIsError] = useState<boolean>(false)

    const onFocusHandler = () => {
        setIsFocused(true)
        setIsError(false)
    }

    const onBlurHandler = () => {
        setIsFocused(false)
        if(!password) setIsError(true)
    }

    return (
        <div className={styles.container}>
            <input 
                type={isVisible ? 'text' : 'password'} 
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                onFocus={onFocusHandler}
                onBlur={onBlurHandler}
                className={isError ? styles.isErrorField : ''}
            />
            <img src={eye} alt="visible" className={styles.visible} onClick={() => setIsVisible(!isVisible)}  />
            <span className={(isFocused || password) ? styles.active : styles.placeholder}>
                Password
            </span>
            {
                isError 
                    ? <span className={styles.errorMessage}>Field is required!</span> 
                    : null
            }
        </div>
    )
}


export default PasswordInput
